# -*- coding: utf-8 -*-
"""Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uIQdpPc-Hwaok-jCTlMXMPuNomht5Dc
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

bmi = pd.read_csv('/content/drive/MyDrive/Dataset/Datasets/BMI.csv')

bmi

bmi['Index'].value_counts()

bmi.plot(kind='scatter',x='Height',y='Weight',c='Index',cmap=plt.get_cmap('rainbow'))

bmi.plot(kind='scatter',x='Height',y='Weight')

"""# **Variance and standard daviation of height**

"""

height_mean = bmi['Height'].mean()
hm = round(height_mean)
hm

hmean = sum(bmi['Height'])/len(bmi['Height'])
hmean

length = len(bmi['Height'])
length

# Variance of height
for i in bmi['Height']:
  height = (i-hm)**2/len(bmi['Height'])
print(height)

import math
# Standard deviation
std_height = math.sqrt(height)
std_height

"""# **Variance and standard daviation of Weight**"""

weight_mean = bmi['Weight'].mean()
wm = round(weight_mean)
wm

# Variance of weight
for i in bmi['Weight']:
  weight = (i-wm)**2/len(bmi['Weight'])
print(weight)

# Standard deviation
std_weight = math.sqrt(weight)
std_weight

"""# **Variance and standard daviation of Index**"""

# Variance of Index
index_mean = round(bmi['Index'].mean())
for i in bmi['Index']:
  index = (i-index_mean)**2/len(bmi['Index'])
print('Variance of index is: ',index)

# standard deviation
std_index = math.sqrt(index)
print('standard deviation of index is: ',std_index)

"""# **Variance and standard daviation of only female**"""

female = bmi[bmi['Gender']=='Female']
female

female_height_mean = female['Height'].mean()
fh = round(female_height_mean)
fh
# Variance
for i in female['Height']:
  female_height = (i-fh)**2/len(female['Height'])
print('Variance of fenail height: ',female_height)
# standard deviation
std_female_height = math.sqrt(female_height)
print('standard deviation of female height: ',std_female_height)

female_weight_mean = female['Weight'].mean()
fw = round(female_weight_mean)
fw
# Variance
for i in female['Weight']:
  female_weight = (i-fw)**2/len(female['Weight'])
print('Variance of fenail weight: ',female_weight)
# standard deviation
std_female_weight = math.sqrt(female_weight)
print('standard deviation of female weight: ',std_female_weight)

female_index_mean = round(female['Index'].mean())
for i in female['Index']:
  female_index = (i-female_index_mean)**2/len(female['Index'])
print('Variance of fenail index: ',female_index)
# standard deviation
std_female_index = math.sqrt(female_index)
print('standard deviation of female index: ',std_female_index)

female.plot(kind='scatter',x='Height',y='Weight',c='Index',cmap=plt.get_cmap('rainbow'))

"""# Visualization"""

sns.boxplot(x='Index',y='Height',data=bmi)

sns.pairplot(bmi.drop("Gender", axis=1), hue="Index", size=5)

sns.pairplot(bmi.drop("Index", axis=1), hue="Gender", size=5)

